#server:
#  port: 8081
#
#person:
#  age: 20
#  boss: false
#  birth: 2017/12/12
#  map: {k1: v1,k2: 12}
#  list:
#    - one
#    - two
#    - three
#  dog:
#    name: helen
#    age: 2
#  last-name: Matty